- 
  name: Install Nginx
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy Webpage
      copy:
        content: "<html><body><h1>Hello, Ansible!</h1></body></html>"
        dest: /var/www/html/index.html
